name: Build & Deploy

on:
  push:
    branches: 
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  NAME: db-proxy
  VERSION: 1.0
  TKE_REGION: ap-shanghai
  TKE_CLUSTER_ID: cls-fo122wzb
  DB_HOST: mongodb
  DB_PORT: 27017
  DB_USER: root
  IMAGE_URL: hub.docker.com
  NAMESPACE: melee-game

jobs:
  go-fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - name: Fmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
  go-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        run: CI=true go test -json ./... > test.json

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.3.0
        with:
          test-results: test.json

  build-push-deploy:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    needs:
      - go-fmt
      - go-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # 通过 Dockerfile 制作镜像
      - name: Build Docker image
        run: |
          docker build --build-arg DB_USER=${{ env.DB_USER }} --build-arg DB_PWD=${{ secrets.DB_PWD}} \
            --build-arg DB_HOST=${{ env.DB_HOST }} --build-arg DB_PORT=${{ env.DB_PORT }} -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.NAME }}:${{ env.VERSION }} .
      # 登录镜像仓库
      - name: Login Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      # 推送镜像至仓库
      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.NAME }}:${{ env.VERSION }}
      # 配置Kustomize
      - name: Set up Kustomize
        run: |
          curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      # 配置kubectl客户端
      - name: Set up ~/.kube/config for connecting TKE cluster
        uses: TencentCloud/tke-cluster-credential-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          tke_region: ${{ env.TKE_REGION }}
          cluster_id: ${{ env.TKE_CLUSTER_ID }}
      # 切换集群环境
      - name: Switch to TKE context
        run: |
          kubectl config use-context ${TKE_CLUSTER_ID}-context-default
      # 更新应用
      - name: Deploy To TKE
        run: |
          (cd deployments && ./../kustomize edit set image ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.NAME }}:${{ env.VERSION }})
          (cd deployments && ./../kustomize build . | kubectl -n ${{ env.NAMESPACE }} apply  -f - )
          kubectl -n ${{ env.NAMESPACE }} rollout status deployment/${{ env.NAME }}
          kubectl -n ${{ env.NAMESPACE }} get services -o wide